### ISSUE TITLE
Port to Unity ?

### ISSUE THREAD

**Issue by BjornNY** [Igrovalnik/DaBlackjack#1]
Hi, please port this game to Unity 5 and export it as WebGL so it can be embeded in websites. :+1: 

I want to help with this, but I am realy new to game development.

**Comment by RoumenDamianoff** [comment]
Yes, I will in near future, but I won't really support this game.. its just a demo for educational purposes.

I am also new to game development :+1:

**Comment by BjornNY** [comment]
:+1:
